import { startServer, launch } from './lib.mjs';
const stop = await startServer();
const browser = await launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('console', (m) => { if (m.type() === 'error') errors.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => errors.push(`[pageerror] ${e.message}\n${e.stack}`));
await page.goto(`http://localhost:4173/?debug=1&mission=2&cp=3&god=1&q=low`);
await page.waitForTimeout(5000);
const ev = (f, a) => page.evaluate(f, a);
const st = () => ev(() => { const g = window.__game; const b = g.enemies.find((e) => e.type === 'boss'); return { state: g.state, cp: g.cp, boss: b && { hp: Math.round(b.hp), ph: b.phase, aware: b.aware, dead: b.dead }, alive: g.enemies.filter((e) => !e.dead).length, gren: g.grenades.length }; });
console.log('start', JSON.stringify(await st()));
await ev(() => { const g = window.__game; g.player.pos.set(0, 0, -72); g.player.yaw = 0; g.player.pitch = 0.0; });
await page.waitForTimeout(3500);
await page.screenshot({ path: 'tests/shots/boss-1.png' });
console.log('arena', JSON.stringify(await st()));
await ev(() => { const g = window.__game; const b = g.enemies.find((e) => e.type === 'boss'); b.hp = b.maxHp * 0.6; b.checkPhase(g); });
await page.waitForTimeout(4000);
await page.screenshot({ path: 'tests/shots/boss-2.png' });
console.log('phase2', JSON.stringify(await st()));
await ev(() => { const g = window.__game; const b = g.enemies.find((e) => e.type === 'boss'); b.invuln = 0; b.hp = b.maxHp * 0.3; b.checkPhase(g); b.invuln = 0; });
await page.waitForTimeout(4000);
await page.screenshot({ path: 'tests/shots/boss-3.png' });
console.log('phase3', JSON.stringify(await st()));
await ev(() => { const g = window.__game; const b = g.enemies.find((e) => e.type === 'boss'); b.invuln = 0; b.takeDamage(99999, true, b.headPos(new g.player.pos.constructor()), new g.player.pos.constructor(0, 0, -1), g, 2); });
await page.waitForTimeout(3000);
await page.screenshot({ path: 'tests/shots/boss-4.png' });
console.log('dead', JSON.stringify(await st()));
await page.waitForTimeout(30000);
console.log('end', JSON.stringify(await st()));
await page.screenshot({ path: 'tests/shots/boss-end.png' });
console.log(errors.slice(0, 10).join('\n'));
await browser.close(); stop();
