import { startServer, launch } from './lib.mjs';
const stop = await startServer();
const browser = await launch();
const page = await browser.newPage({ viewport: { width: 960, height: 540 } });
const errs = [];
page.on('pageerror', (e) => errs.push(e.message + '\n' + e.stack));
await page.goto(`http://localhost:4173/?debug=1&mission=1&god=1&q=low&loadout=hornet,breaker`);
await page.waitForTimeout(5000);
await page.evaluate(() => { const g = window.__game; g.player.pos.set(0, 0, 60); g.player.yaw = 0; g.player.pitch = 0.05; });
await page.waitForTimeout(1200);
await page.screenshot({ path: 'tests/shots/gun-hornet.png', clip: { x: 480, y: 270, width: 480, height: 270 } });
await page.keyboard.press('Digit2'); await page.waitForTimeout(1500);
await page.screenshot({ path: 'tests/shots/gun-breaker.png', clip: { x: 480, y: 270, width: 480, height: 270 } });
await page.mouse.down(); await page.waitForTimeout(300); await page.mouse.up(); await page.waitForTimeout(150);
await page.screenshot({ path: 'tests/shots/gun-breaker-fire.png' });
console.log(errs.join('\n'));
await browser.close(); stop();
const stop2 = await startServer(4174);
const b2 = await launch();
const p2 = await b2.newPage({ viewport: { width: 960, height: 540 } });
await p2.goto(`http://localhost:4174/?debug=1&mission=1&god=1&q=low&loadout=longbow,vk7`);
await p2.waitForTimeout(5000);
await p2.evaluate(() => { const g = window.__game; g.player.pos.set(0, 0, 60); g.player.yaw = 0; g.player.pitch = 0.02; });
await p2.waitForTimeout(1200);
await p2.screenshot({ path: 'tests/shots/gun-longbow.png', clip: { x: 480, y: 270, width: 480, height: 270 } });
await p2.evaluate(() => { window.__game.input.buttons.add(2); });
await p2.waitForTimeout(3500);
await p2.screenshot({ path: 'tests/shots/gun-longbow-ads.png' });
await b2.close(); stop2();
