import { startServer, launch } from './lib.mjs';
const stop = await startServer();
const browser = await launch();
const page = await browser.newPage({ viewport: { width: 640, height: 360 } });
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
await page.goto(`http://localhost:4173/?debug=1&mission=2&cp=0&god=1&q=low`);
await page.waitForTimeout(5000);
await page.evaluate(() => { const g = window.__game; g.hud.show(false); g.viewmodel.root.visible = false; for (const e of g.enemies) g.scene.remove(e.rig.root); g.player.pos.set(-30, 0, -43); g.player.yaw = 0; g.player.pitch = 0.1; });
await page.waitForTimeout(800);
const get = () => window.__game.level.group.children.find((c) => c.material && c.material.metalness > 0.2 && c.material.metalness < 0.3);
const meanLuma = async (clip) => { const b = await page.screenshot({ clip }); return page.evaluate(async (b64) => { const img = new Image(); img.src = 'data:image/png;base64,' + b64; await img.decode(); const c = document.createElement('canvas'); c.width = img.width; c.height = img.height; const x = c.getContext('2d'); x.drawImage(img, 0, 0); const d = x.getImageData(0, 0, c.width, c.height).data; let s = 0; for (let k = 0; k < d.length; k += 4) s += d[k] + d[k + 1] + d[k + 2]; return Math.round(s / (d.length / 4) / 3); }, b.toString('base64')); };
const clip = { x: 200, y: 180, width: 200, height: 60 };
console.log('base', await meanLuma(clip));
await page.evaluate(() => { const m = (window.__game.level.group.children.find((c) => c.material && c.material.metalness > 0.2 && c.material.metalness < 0.3)).material; m.vertexColors = false; m.color.set(0x888888); m.needsUpdate = true; });
await page.waitForTimeout(600); console.log('no vertex colors', await meanLuma(clip));
await page.evaluate(() => { const m = (window.__game.level.group.children.find((c) => c.material && c.material.metalness > 0.2 && c.material.metalness < 0.3)).material; m.map = null; m.needsUpdate = true; });
await page.waitForTimeout(600); console.log('no map', await meanLuma(clip));
await page.evaluate(() => { const m = (window.__game.level.group.children.find((c) => c.material && c.material.metalness > 0.2 && c.material.metalness < 0.3)).material; m.metalness = 0; m.needsUpdate = true; });
await page.waitForTimeout(600); console.log('metalness 0', await meanLuma(clip));
await page.evaluate(() => { const g = window.__game; const m = (g.level.group.children.find((c) => c.material && c.material.metalness > 0.2 && c.material.metalness < 0.3)); m.receiveShadow = false; });
await page.waitForTimeout(600); console.log('no receiveShadow', await meanLuma(clip));
console.log(errs.join('\n'));
await browser.close(); stop();
