import { chromium } from 'playwright';
import { startServer, launch } from './lib.mjs';
const stop = await startServer();
const browser = await launch();
const ctx = await browser.newContext({ viewport: { width: 844, height: 390 }, hasTouch: true, isMobile: true, deviceScaleFactor: 2 });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(`[pageerror] ${e.message}`));
await page.goto(`http://localhost:4173/?debug=1`);
await page.waitForTimeout(3000);
await page.screenshot({ path: 'tests/shots/mob-title.png' });
await page.tap('#m-play'); await page.waitForTimeout(500);
await page.screenshot({ path: 'tests/shots/mob-missions.png' });
await page.tap('.mcard[data-id="1"]'); await page.waitForTimeout(500);
await page.screenshot({ path: 'tests/shots/mob-brief.png' });
await page.tap('#deploy'); await page.waitForTimeout(6000);
console.log('touch?', await page.evaluate(() => window.__game.input.isTouch + ' ' + window.__game.state));
await page.screenshot({ path: 'tests/shots/mob-play.png' });
console.log(errors.join('\n'));
await browser.close(); stop();
