import { startServer, launch } from './lib.mjs';
const stop = await startServer();
const browser = await launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('console', (m) => { if (m.type() === 'error') errors.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => errors.push(`[pageerror] ${e.message}\n${e.stack}`));
await page.goto(`http://localhost:4173/?debug=1&mission=1&q=low`);
await page.waitForTimeout(5000);
const pos = () => page.evaluate(() => { const p = window.__game.player; return [p.pos.x.toFixed(1), p.pos.y.toFixed(2), p.pos.z.toFixed(1), p.speed.toFixed(1)].join(','); });
console.log('start', await pos());
await page.keyboard.down('KeyW');
await page.waitForTimeout(3000);
console.log('walk', await pos());
await page.keyboard.down('ShiftLeft');
await page.waitForTimeout(2000);
console.log('sprint', await pos());
await page.keyboard.up('ShiftLeft'); await page.keyboard.up('KeyW');
await page.keyboard.press('Space');
await page.waitForTimeout(250);
console.log('jump', await pos());
await page.waitForTimeout(1500);
// reload and ammo
await page.keyboard.down('Digit1');
await page.mouse.down(); await page.waitForTimeout(1500); await page.mouse.up();
console.log('ammo after fire', await page.evaluate(() => window.__game.weapons.cw.mag));
await page.keyboard.press('KeyR'); await page.waitForTimeout(4000);
console.log('ammo after reload', await page.evaluate(() => window.__game.weapons.cw.mag + '/' + window.__game.weapons.cw.reserve));
await page.keyboard.press('KeyQ'); await page.waitForTimeout(800);
console.log('weapon', await page.evaluate(() => window.__game.weapons.def.name));
// take damage until death
await page.evaluate(() => window.__game.damagePlayer(1000, window.__game.player.pos.clone().add(window.__game.player.pos.constructor.prototype.constructor === undefined ? 0 : { x: 5, y: 0, z: 5, clone() { return this; } })));
await page.waitForTimeout(3500);
console.log('state after death', await page.evaluate(() => window.__game.state));
await page.screenshot({ path: 'tests/shots/death.png' });
await page.click('#g-rs');
await page.waitForTimeout(3500);
console.log('after restart', await page.evaluate(() => window.__game.state + ' hp=' + window.__game.player.health));
console.log(errors.slice(0, 10).join('\n'));
await browser.close(); stop();
