import { startServer, launch } from './lib.mjs';
const stop = await startServer();
const browser = await launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errs = [];
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
page.on('pageerror', (e) => errs.push(e.message + '\n' + e.stack));
await page.goto(`http://localhost:4173/?debug=1`);
await page.waitForTimeout(2500);
const st = () => page.evaluate(() => window.__game.state + ' m' + window.__game.missionId + ' cp' + window.__game.cp);
await page.click('#m-set'); await page.waitForTimeout(300);
await page.screenshot({ path: 'tests/shots/ui-settings.png' });
await page.click('.set .chip[data-q="low"]'); await page.waitForTimeout(300);
await page.click('.screen.on #back'); await page.waitForTimeout(300);
await page.click('#m-ctl'); await page.waitForTimeout(300);
await page.screenshot({ path: 'tests/shots/ui-controls.png' });
await page.click('.screen.on #back'); await page.waitForTimeout(300);
await page.click('#m-play'); await page.waitForTimeout(300);
await page.screenshot({ path: 'tests/shots/ui-missions.png' });
await page.click('.mcard[data-id="1"]'); await page.waitForTimeout(300);
await page.click('.wcard[data-w="breaker"]'); await page.waitForTimeout(200);
await page.click('.screen.on #deploy'); await page.waitForTimeout(4500);
console.log('deployed', await st(), await page.evaluate(() => window.__game.weapons.slots.map((s) => s.def.name).join(',')));
await page.evaluate(() => window.__game.pause(true)); await page.waitForTimeout(400);
await page.screenshot({ path: 'tests/shots/ui-pause.png' });
await page.click('#p-rs'); await page.waitForTimeout(4000);
console.log('restart', await st());
await page.evaluate(() => window.__game.pause(true)); await page.waitForTimeout(300);
await page.click('#p-q'); await page.waitForTimeout(2500);
console.log('quit', await st());
await page.click('#m-play'); await page.waitForTimeout(300);
await page.click('.mcard[data-id="2"]'); await page.waitForTimeout(300);
await page.click('.screen.on #deploy'); await page.waitForTimeout(4500);
console.log('m2', await st());
await page.screenshot({ path: 'tests/shots/ui-m2.png' });
console.log(errs.join('\n'));
await browser.close(); stop();
